"""Add 'ads' and 'companies' tables

Revision ID: 1fd63fea9899
Revises: 
Create Date: 2023-02-11 13:27:48.105269

"""
from alembic import op
import sqlalchemy as sa
from schemas.ads import ad_id_seq, company_id_seq


# revision identifiers, used by Alembic.
revision = '1fd63fea9899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(sa.schema.CreateSequence(ad_id_seq))
    op.execute(sa.schema.CreateSequence(company_id_seq))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_created_date', sa.DateTime(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_hq_city', sa.String(), nullable=True),
    sa.Column('company_hq_country', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_size', sa.Integer(), nullable=True),
    sa.Column('company_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_companies')),
    sa.UniqueConstraint('company_name', 'company_hq_country', 'company_hq_city', name=op.f('uq_companies_company_name'))
    )
    op.create_table('ads',
    sa.Column('ad_category', sa.String(), nullable=True),
    sa.Column('ad_company_id', sa.Integer(), nullable=True),
    sa.Column('ad_created_date', sa.DateTime(), nullable=False),
    sa.Column('ad_id', sa.BigInteger(), server_default=sa.text("nextval('ad_id_seq')"), nullable=False),
    sa.Column('ad_expired', sa.Boolean(), nullable=True),
    sa.Column('ad_fully_remote', sa.Boolean(), nullable=True),
    sa.Column('ad_main_technology', sa.String(length=32), nullable=True),
    sa.Column('ad_online_intereview', sa.Boolean(), nullable=True),
    sa.Column('ad_posted_date', sa.DateTime(), nullable=False),
    sa.Column('ad_b2b_available', sa.Boolean(), nullable=True),
    sa.Column('ad_permanent_available', sa.Boolean(), nullable=True),
    sa.Column('ad_salary_b2b_currency', sa.String(), nullable=True),
    sa.Column('ad_salary_b2b_from', sa.Integer(), nullable=True),
    sa.Column('ad_salary_b2b_to', sa.Integer(), nullable=True),
    sa.Column('ad_salary_permanent_from', sa.Integer(), nullable=True),
    sa.Column('ad_salary_permanent_currency', sa.String(), nullable=True),
    sa.Column('ad_salary_permanent_to', sa.Integer(), nullable=True),
    sa.Column('ad_src', sa.String(), nullable=False),
    sa.Column('ad_title', sa.String(), nullable=False),
    sa.Column('ad_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ad_company_id'], ['companies.company_id'], name=op.f('fk_ads_ad_company_id_companies')),
    sa.PrimaryKeyConstraint('ad_id', name=op.f('pk_ads')),
    sa.UniqueConstraint('ad_src', 'ad_url', 'ad_posted_date', name=op.f('uq_ads_ad_src'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ads')
    op.drop_table('companies')
    op.execute(sa.schema.DropSequence(ad_id_seq))
    op.execute(sa.schema.DropSequence(company_id_seq))
    # ### end Alembic commands ###
